#!/usr/bin/python
from docopt import docopt
import json
import os
import sys
import sys
import collections
from sh import pfctl, echo, ifconfig

ROOT_CONFIG_FILE = os.path.expanduser("~/.dottest-config")
SPECIFIC_CONFIG_FILE = os.path.join(os.getcwd(), ".dottest-config")
RULES_FILE = os.path.expanduser("~/.dottest-rules")


def eprint(*args, **kwargs):
    """Print to stderr."""
    print(*args, file=sys.stderr, **kwargs)


def require_sudo():
    """If we are not running as root, re-run as root."""
    if os.geteuid() != 0:
        os.execvp("sudo", ["sudo"] + sys.argv)


class DotTest:

    def __init__(self):
        self.read_config()
        self.read_rules()

    def read_config(self):
        self._config = {
            "domain_suffix": ".test",
            "address_prefix": "127.0.0."
        }
        if os.path.exists(ROOT_CONFIG_FILE):
            with open(ROOT_CONFIG_FILE, "r") as i:
                self._config.update(dict(l.strip().split("=", 1) for l in i.readlines()))
        if os.path.exists(SPECIFIC_CONFIG_FILE):
            with open(SPECIFIC_CONFIG_FILE, "r") as i:
                self._config.update(dict(l.strip().split("=", 1) for l in i.readlines()))

        if not self._config["address_prefix"].endswith(".") or not self._config["address_prefix"].count(".") == 3:
            eprint("Error: Invalid address prefix %s" % self._config["address_prefix"])
            sys.exit(1)

    def read_rules(self):
        self._rules = collections.OrderedDict()
        if os.path.exists(RULES_FILE):
            with open(RULES_FILE, "r") as i:
                self._rules.update(collections.OrderedDict(l.strip().split("=", 1) for l in i.readlines() if not l.strip() == ""))

    def write_rules(self):
        with open(RULES_FILE, "w") as o:
            for domain, port in self._rules.items():
                o.write("%s=%s\n" % (domain, port))

    def refresh_system(self):
        self._refresh_hosts()
        self._refresh_ifconfig()
        self._refresh_ports()

    def _refresh_hosts(self):
        with open("/etc/hosts", "r") as o:
            lines = o.readlines()

        # First strip out all existing ones with our prefix
        lines = [l for l in lines if not l.startswith(self._config["address_prefix"]) or l.startswith(self._config["address_prefix"] + "1")]

        n = 2
        for domain, port in self._rules.items():
            lines.append("%s%s\t%s\n" % (self._config["address_prefix"], n, domain))
            n += 1

        with open("/etc/hosts", "w") as o:
            for line in lines:
                o.write(line)

    def _refresh_ifconfig(self):
        n = 2
        for domain, port in self._rules.items():
            ifconfig("lo0", "alias", "%s%s" % (self._config["address_prefix"], n))
            n += 1

    def _refresh_ports(self):
        rules = pfctl("-s", "all")
        if "TRANSLATION RULES" in rules:
            rules = [l.strip() for l in rules.split("TRANSLATION RULES:", 1)[1].split("FILTER", 1)[0].split("\n") if l.strip() != ""]
            rules = [l for l in rules if self._config["address_prefix"] not in l]
        else:
            rules = []

        n = 2
        for domain, port in self._rules.items():
            rules.append("rdr pass on lo0 inet proto tcp from any to %s%s port 80 -> 127.0.0.1 port %s" % (self._config["address_prefix"], n, port))
            n += 1

        try:
            pfctl("-ef", "-", _in=echo("\n".join(current_rules)))
        except:
            # It always throws because of a warning. Ignore it
            pass

    def add(self, domain, port):
        if not domain.endswith(self._config["domain_suffix"]):
            eprint("Error '%s' does not end with %s" % (domain, self._config["domain_suffix"]))
            sys.exit(1)
        self._rules[domain] = port

    def remove(self, domain):
        if domain not in self._rules:
            eprint("Domain %s not configured" % domain)
            sys.exit(1)
        del self._rules[domain]

    def list(self):
        for domain, port in self._rules.items():
            print("%s points to localhost:%s" % (domain, port))

    def clear(self):
        self._rules = {}

    def get_dottest_rules(self, path):
        dottest_path = os.path.join(path, ".dottest")
        directory_module_name = os.path.split(path)[1]

        if os.path.isfile(dottest_path):
            with open(dottest_path, "r") as o:
                values = [l.strip().split("=") for l in o]
                kv = {v[0]: v[1] for v in values}
                return kv

        return {}

    def auto(self, path):
        dottest_rules = self.get_dottest_rules(path)
        for domain, port in dottest_rules.items():
            self.add(domain, port)

        for f in os.listdir(path):
            subdir = os.path.join(path, f)
            if os.path.isdir(subdir):
                self.auto(subdir)


__doc__ = """dotTest - Local .test domains
Usage:
dottest add <domain> <port>
dottest remove <domain>
dottest list
dottest clear
dottest init
dottest auto [path]
"""

arguments = docopt(__doc__, version="dotTest 0.1")

require_sudo()
dottest = DotTest()
if arguments["list"]:
    dottest.list()
    sys.exit(0)
elif arguments["add"]:
    dottest.add(arguments["<domain>"], int(arguments["<port>"]))
elif arguments["remove"]:
    dottest.remove(arguments["<domain>"])
elif arguments["auto"]:
    path = os.getcwd() if not arguments["path"] else arguments["path"]
    dottest.auto(path)
elif arguments["clear"]:
    dottest.clear()

dottest.write_rules()
dottest.refresh_system()
